name: Run Action Tests

on: 
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Actions
      run: | 
        EXPECTED="ABC"
        ACTUAL="ABD"

        [ "$EXPECTED" = "$ACTUAL" ]
  
        return 0
        
